POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "madhu_gorava",
  "name": "Madhu Gorava",
  "password": "jack_9381",
  "gender": "male",
  "location": "Hyderabad"
}


###
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "adam_richard",
  "password": "richard_567"
}
### 
PUT http://localhost:3000/change-password
Content-Type: application/json

{
  "username": "adam_richard",
  "oldPassword": "richard_567",
  "newPassword": "richard@123"
}
